<?php


namespace Kdyby\RabbitMq\Command;


use Symfony\Component\Console\Command\Command;

abstract class BaseCommand extends Command
{
	protected $namespace;
	protected $alias;

	public function __construct(string $name = null, string $namespace = 'kdybyrabbitmq', string $alias = null)
	{
		$this->alias = $alias;
		$this->namespace = $namespace;

		parent::__construct($name);
	}

	public function setName($name)
	{
		return parent::setName($this->computeName($name)); // TODO: Change the autogenerated stub
	}

	protected function computeName(string $name): string
	{
		return $this->namespace . ':' . $name;
	}

	protected function computeAlias(string $name): ?string
	{
		return ($this->alias === null ? null : $this->alias . ':' . $name);
	}
}